---
  - name: Install nginx
    yum: name=nginx state=latest
    become: yes

  - name: start nginx
    service: name=nginx state=started enabled=true

  - name: Copy nginx.conf
    become: yes
    template:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf  

